"""Add coupon fields to course payments

Revision ID: 278c9465704f
Revises: 2cd8c371fcf0
Create Date: 2026-08-17 20:34:43.869840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278c9465704f'
down_revision: Union[str, Sequence[str], None] = '2cd8c371fcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_payments', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('coupon_id')
        batch_op.drop_column('coupon_code')

    # ### end Alembic commands ###
